# H2 In-Memory Database (Kurulum gerektirmez)
spring.datasource.url=jdbc:h2:mem:patient_monitoring;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# H2 Console (tarayicidan veritabanini gormek icin: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.security=DEBUG

# Fitbit API
fitbit.client.id=23QBSD
fitbit.client.secret=73656cba9510091b4d827a5e3b029ab6
fitbit.redirect.uri=http://localhost:8080/api/fitbit/callback